{{- if and .Values.operator.metrics.enabled .Values.operator.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gress-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gress-operator.labels" . | nindent 4 }}
    {{- with .Values.operator.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gress-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.operator.metrics.serviceMonitor.interval }}
    {{- with .Values.operator.metrics.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}
